.TH galinette 1

.SH NAME
galinette - GUI flash utility for Flymaster® B1 avionics devices.

.SH SYNOPSIS
.B galinette

.SH DESCRIPTION
Graphical utility for updating the firmware on Flymaster® B1 avionics devices.

.SH SEE ALSO
.BR galinette-flash (1)

.SH AUTHORS
Written by Boris Lechner.

Man page written to conform with Debian by Paul McEnery.
