.TH galinette-flash 1

.SH NAME
galinette-flash - CLI flash utility for Flymaster® B1 avionics devices.

.SH SYNOPSIS
.B galinette-flash
[OPTIONS] FILE

.SH DESCRIPTION
Command line utility for updating the firmware on Flymaster® B1 avionics devices.

.SH OPTIONS
.B -s
USB serial device.

.SH FILE
Firmware file (*.b1b) which can be obtained from Flymaster®.

.SH SEE ALSO
.BR galinette (1)

.SH AUTHORS
Written by Boris Lechner.

Man page written to conform with Debian by Paul McEnery.
